force-app/main/default/objects/A__c/A__c.object-meta.xml
<CustomObject>
    <label>A</label>
    <nameField>
        <label>Nome de A</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B__c/B__c.object-meta.xml
<CustomObject>
    <label>B</label>
    <nameField>
        <label>Nome de B</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>A</label>
    <referenceTo>A__c</referenceTo>
    <relationshipLabel>B</relationshipLabel>
    <relationshipName>B</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/C__c/C__c.object-meta.xml
<CustomObject>
    <label>C</label>
    <nameField>
        <label>Nome de C</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B</label>
    <referenceTo>B__c</referenceTo>
    <relationshipLabel>C</relationshipLabel>
    <relationshipName>C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/relatedListviewControllerTest.cls
/**
 * @description       : Test class for relatedListviewController
 * @author            : Gabriela
 * @group             : 
 * @last modified on  : 08-05-2021
 * @last modified by  : Gabriela
**/
@IsTest
public with sharing class relatedListviewControllerTest {
    
    @testSetup 
    static void setup() {

        List<B__c> bList = new List<B__c>();
        List<C__c> cList = new List<C__c>();
        Integer registerCount = 100;

        A__c a = new A__c(Name = 'A1');
        insert A;
        
        for(Integer i=0; i<registerCount; i++){
            B__c b = new B__c(Name='B'+i, A__c = a.Id);
            bList.add(b);
        }
        insert bList;
        
        for(B__c b : bList){
            C__c c = new C__c(Name = 'C - '+ b.Name, B__c = b.Id);
            cList.add(c);
        }
		insert cList;
    }

    @isTest
    static void testRelatedListComponent(){

        A__c a = [SELECT Id FROM A__c WHERE Name = 'A1'];
        
        List<SObject> sObjectList = relatedListviewController.getRecordsList(a.Id);
        
        System.assertEquals(200, sObjectList.size());
    }
}