force-app/main/default/objects/A__c/A__c.object-meta.xml
<CustomObject>
    <label>A</label>
    <nameField>
        <label>Nome de A</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B__c/B__c.object-meta.xml
<CustomObject>
    <label>B</label>
    <nameField>
        <label>Nome de B</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>A</label>
    <referenceTo>A__c</referenceTo>
    <relationshipLabel>B</relationshipLabel>
    <relationshipName>B</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/C__c/C__c.object-meta.xml
<CustomObject>
    <label>C</label>
    <nameField>
        <label>Nome de C</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B</label>
    <referenceTo>B__c</referenceTo>
    <relationshipLabel>C</relationshipLabel>
    <relationshipName>C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/relatedListviewController.cls
/**
 * @description       : Controller class for the component relatedListview
 * @author            : Gabriela
 * @group             : 
 * @last modified on  : 08-04-2021
 * @last modified by  : Gabriela
**/
public with sharing class relatedListviewController {

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordsList(Id aId){
        System.debug('AQUI CONTROLER');
    	List<SObject> recordList = new List<SObject>();
        Set<Id> BSetId = new Set<Id>();

        for(B__c b : [SELECT Id, Name, Owner.Name, CreatedDate FROM B__c WHERE A__c =: aId]){   
            BSetId.add(b.Id);
            recordList.add(b);
        }
		System.debug('B: ' + recordList.size());
        System.debug(BSetId);
        for(C__c c : [SELECT Id, Name, Owner.Name, CreatedDate FROM C__c WHERE B__c IN: BSetId]){
            System.debug('C' + c);
            recordList.add(c);
        }

        return recordList;
    }
}